### ISSUE TITLE
Store::set and friends deep clone the properties set is a bit of an issue

### ISSUE THREAD

**Issue by kastermester** [miklschmidt/capacitor.js#1]
Ie. I want to store a React component in my store and now my entire component is borked.

Could a different strategy perhaps instead be to utilize the react immutability helpers and then add a guideline that says that you cannot alter what is stored inside the store after a store? It seems a bit odd that my data gets altered just because I want to store it in my store.

**Comment by kastermester** [comment]
I might try and supply a patch that would show how I would go about doing it. Also, this would aid in using the PureRenderMixin from React, as the data that has not changed would remain unaltered in the store.

**Comment by miklschmidt** [comment]
> add a guideline that says that you cannot alter what is stored inside the store after a store

Just to sum up what we discussed offline, Immutable-js is now used to enforce this guideline, ensuring immutability and allow the use of PureRenderMixin. Unfortunately this breaks backwards compatibility. The data returned by the stores is now instances of immutable-js classes. This has been implemented in 0.2.0.
