### ISSUE TITLE
Optimize add() in ListStore and IndexedListStore

### ISSUE THREAD

**Issue by miklschmidt** [miklschmidt/capacitor.js#7]
The problem: in an action handler for an indexed list store i might add items this way:

``` coffeescript
@add data.index, id for id in data.ids
```

This will create a new list in each iteration, which is terrible for performance. Instead if we automatically duplicated the stores `@_properties` as a mutable temporary value within an action handler, we could avoid the cost of creating all these temporary immutable's. Another option is to add a `withMutations` method to the store, to reflect the ImmutableJS API.

**Comment by miklschmidt** [comment]
Come to think of it, moving all the state into the dispatcher, and simply making the global state mutable within the dispatch cycle might not be a terrible idea.

**Comment by miklschmidt** [comment]
So i did some experimenting.. Making the state mutable has little to no performance impact. What makes the `@add` slow is the `currentIds.includes(id)` which makes sense. Pushing 10k ids by subsequently calling `@add` takes over 6secs for me. Removing that line gets it down to 24ms.. Now if i pass an array to `@add` with 10k items i can get that down to 16ms (i figure that's all the type checking and `@get()` calls). Does it even make sense for the ListStore to enforce uniqueness of id's in the list @kastermester? If so, maybe we should make it an `Immutable.Map` instead?

**Comment by miklschmidt** [comment]
I'd still like to move the state into the dispatcher for other reasons, but in this case it makes no difference.

**Comment by kastermester** [comment]
I don't think it does. You might want a list with duplicates.

**Comment by miklschmidt** [comment]
Yea that's what i was thinking. Well, that makes the fix pretty easy!

**Comment by miklschmidt** [comment]
Fix implemented
